version: '2.2'
services:
  api:
    build: .
    init: true
    image: registry.plat2.leonidasoy.fi/leonidas-platform-kontena-exporter
    ports:
      - 3000:3000
    environment:
      KONTENA_EXPORTER_ACCESS_TOKEN: ${KONTENA_EXPORTER_ACCESS_TOKEN}
