version: '2.2'
services:
  test:
    build: .
    init: true
    image: registry.plat2.leonidasoy.fi/leonidas-platform-kontena-exporter
    command: node_modules/.bin/mocha --require src/helpers/testHelper.js src/**/*.test.ts
    environment:
      NODE_ENV: test
