stack: santtu-pajukanta-leonidas/kontena-exporter
version: '0.1.0'

variables:
  prometheus_password:
    type: string
    from:
      vault: ${STACK}_prometheus_password
      random_string: 63
    to:
      vault: ${STACK}_prometheus_password

services:
  api:
    image: registry.plat2.leonidasoy.fi/leonidas-platform-kontena-exporter
    instances: 1
    secrets:
      - secret: KONTENA_MASTER_ACCESS_TOKEN
        name: KONTENA_EXPORTER_ACCESS_TOKEN
        type: env
    environment:
      NODE_ENV: production
      KONTENA_EXPORTER_PASSWORD: ${prometheus_password}

      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 3000
      KONTENA_LB_VIRTUAL_HOSTS: kontena-exporter.plat2.leonidasoy.fi
      KONTENA_LB_CUSTOM_SETTINGS: |
        redirect scheme https if !{ ssl_fc }
        http-response set-header Strict-Transport-Security max-age=16000000;\ includeSubDomains;\ preload;
    links:
      - platform/lb1
